/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpackage;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class JFrameEncriptador extends javax.swing.JFrame {

    /**
     *
     */
    
    
    public JFrameEncriptador() {
        initComponents();
        setSize(780,600);
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        textField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        textShow = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Encriptador");
        setBackground(new java.awt.Color(51, 51, 255));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Descriptografar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(430, 290, 250, 50);

        textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldActionPerformed(evt);
            }
        });
        getContentPane().add(textField);
        textField.setBounds(70, 200, 670, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Criptografar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(120, 290, 250, 50);

        textShow.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textShow.setForeground(new java.awt.Color(255, 255, 255));
        textShow.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        textShow.setAutoscrolls(true);
        textShow.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textShow.setDoubleBuffered(true);
        textShow.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        textShow.setMaximumSize(new java.awt.Dimension(56, 22));
        textShow.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(textShow);
        textShow.setBounds(30, 420, 740, 60);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Criado e programado por Igor Matheus De Souza ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 510, 350, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Background.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -30, 810, 660);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String text=textField.getText();
        
        StringBuilder texto=new StringBuilder(text);
        
        String id1=""+text.charAt(text.length()-3);
        String id2=""+text.charAt(text.length()-2);
        String id3=""+text.charAt(text.length()-1);
        String id4=""+text.charAt(1);
        String id5=""+text.charAt(0);
        
        
        texto.deleteCharAt(0);
         
        texto.deleteCharAt(0);
        
        texto.deleteCharAt(texto.length()-1);
        
        texto.deleteCharAt(texto.length()-1); 
        
        texto.deleteCharAt(texto.length()-1);
      
        text=""+texto;
       
        text=text.replaceAll(id1,"A");
        
        text=text.replaceAll(id2," ");
        text=text.replaceAll(id3,"E");
        text=text.replaceAll(id4,"C");
        
        text=text.replaceAll(id5,"D");
        
       
       
       text=text.replaceAll("3","Ç");
        text=text.replaceAll("ú","B");
        text=text.replaceAll("s","F");
        text=text.replaceAll("<","G");
        text=text.replaceAll("2","H"); 
        text=text.replaceAll(">","I");
        text=text.replaceAll("f","J");
        text=text.replaceAll("0","L");
        text=text.replaceAll("6","K");
        text=text.replaceAll("ç","M");
        text=text.replaceAll("-","N");
        text=text.replaceAll("4","O");
        text=text.replaceAll("1","P");
        text=text.replaceAll("x","Q");
        text=text.replaceAll("9","R");
        text=text.replaceAll("v","S");
        text=text.replaceAll("b","T");
        text=text.replaceAll("5","U");
        text=text.replaceAll("m","V");
        text=text.replaceAll(":","X");
        text=text.replaceAll("]","W");
        text=text.replaceAll("^","Y");
        text=text.replaceAll("é","Z");
        text=text.replaceAll("_","0");
        text=text.replaceAll("z",",");
       
        
        
         text=text.replaceAll("c","1");
        text=text.replaceAll("=","2");
        text=text.replaceAll("k","3");
        text=text.replaceAll("q","4");
        text=text.replaceAll(";","5");
        text=text.replaceAll("e","6");
        text=text.replaceAll("l","7");
        text=text.replaceAll("y","8");
        text=text.replaceAll("t","9");
        text=text.replaceAll("r","ã");
        
        text=text.replaceAll("i","á");
        text=text.replaceAll("o","à");
        text=text.replaceAll("a","í");
        text=text.replaceAll("ñ","õ");
        text=text.replaceAll("ü","y");
        
        text=text.toLowerCase();
        StringBuilder texto2=new StringBuilder(text);
        texto2.deleteCharAt(0);
        text=""+texto2;
        textShow.setText(text);
        textField.setText(text);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String text=textField.getText().toLowerCase();
       //generate a random number
      
       
       if(text.length()>0){
       String[]letras=new String[]{"a"," ","e","c","d"} ;
       String[]letrasCrip=new String[5];
       int[] norepeat=new  int[]{11,11,11,11,11};
       
      
       for(int i=0;i<letras.length;i++){
           
         int alea = aleatorio();
         boolean valid=true;
         
         
            for(int i2=0 ; i2<5 ; i2++){
                if(alea==norepeat[i2]){
                  valid=false;
                  --i;
                }    
            }
         norepeat[i]=alea;
       if(valid){
             if(alea==0){
                 letrasCrip[i]="!";
             };
              if(alea==1){
                 letrasCrip[i]="Ó";
             };
              if(alea==2){
                 letrasCrip[i]="D";             
             };
              if(alea==3){
                 letrasCrip[i]="%";
             }
              if(alea==4){
                 letrasCrip[i]="W";
             }
              if(alea==5){
                 letrasCrip[i]="G";
             };
              if(alea==6){
                 letrasCrip[i]="H";
             };
              if(alea==7){
                 letrasCrip[i]="P";
             };
              if(alea==8){
                 letrasCrip[i]="J";
             };
              if(alea==9){
                 letrasCrip[i]="Â";
             };
              if(alea==10){
                 letrasCrip[i]="U";
             };
          }   
       
     }
       
       
       
      text=text.replaceAll("ú","u");
      text=text.replaceAll("ó","o");
      ;
      
      
      
        text=text.replaceAll("a",letrasCrip[0]);
        text=text.replaceAll(" ",letrasCrip[1]);
        text=text.replaceAll("e",letrasCrip[2]);
        text=text.replaceAll("c",letrasCrip[3]);
        text=text.replaceAll("d",letrasCrip[4]);
        
        text=text.replaceAll("0","_");
        text=text.replaceAll("1","C");
        text=text.replaceAll("2","=");
        text=text.replaceAll("3","K");
        text=text.replaceAll("4","Q");  
        text=text.replaceAll("5",";");
        text=text.replaceAll("6","E");
        text=text.replaceAll("7","L");
        text=text.replaceAll("8","Y");
        text=text.replaceAll("9","T");
        text=text.replaceAll("ã","R");
        text=text.replaceAll("ç","3");
        text=text.replaceAll("á","I");
        text=text.replaceAll("à","O");
        text=text.replaceAll("í","A");
        text=text.replaceAll("õ","Ñ");
        
        
        text=text.replaceAll("b","Ú");
        text=text.replaceAll("f","S");
        text=text.replaceAll("g","<");
        text=text.replaceAll("h","2");
        text=text.replaceAll("i",">");
        text=text.replaceAll("j","F");
        text=text.replaceAll("l","0");
        text=text.replaceAll("k","6");
        text=text.replaceAll("m","Ç");
        text=text.replaceAll("n","-");
        text=text.replaceAll("o","4");
        text=text.replaceAll("p","1");
        text=text.replaceAll("q","X");
        text=text.replaceAll("r","9");
        text=text.replaceAll("s","V");
        text=text.replaceAll("t","B");
        text=text.replaceAll("u","5");
        text=text.replaceAll("v","M");
        text=text.replaceAll("x",":");
        text=text.replaceAll("w","]");
        text=text.replaceAll("y","ü");
        text=text.replaceAll("z","É");
        text=text.replaceAll(",","Z");
        
      
        
        
        StringBuilder texto=new StringBuilder(text);
        for(int i=0;i<5;i++){
            if(i<3){
                texto.append(letrasCrip[i]);
            }
            if(i>2){
                texto.insert(0,letrasCrip[i]);
            }
        }
        text=""+texto;
        
       text=text.toLowerCase();
        textShow.setText(text);
        textField.setText(text);
        
        
       }  
    }//GEN-LAST:event_jButton2ActionPerformed
public static int aleatorio(){
        
         double de=Math.round(Math.random()*10);
        int i=(int)de;
        return i;
};
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEncriptador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEncriptador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEncriptador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEncriptador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEncriptador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JTextField textField;
    private javax.swing.JLabel textShow;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png"))); 
        
    }
}
